title: "Drew Skillman"
tagline: "PLAYABLE REALITIES"
description: "Recreation of the Drew Skillman portfolio homepage."
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  experiences:
    output: true
    permalink: /experiences/:name/

defaults:
  - scope:
      path: ""
      type: experiences
    values:
      layout: experience

url: "https://dskill.github.io"
baseurl: "/website"
