title: "Drew Skillman"
tagline: "INTERACTIVE ARTIFACTS"
description: "Recreation of the Drew Skillman portfolio homepage."
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  experiences:
    output: true
    permalink: /experiences/:name/
  devlog:
    output: true
    permalink: /devlog/:name/
  talks:
    output: true
    permalink: /talks/:name/

defaults:
  - scope:
      path: ""
      type: experiences
    values:
      layout: experience
  - scope:
      path: ""
      type: devlog
    values:
      layout: devlog
  - scope:
      path: ""
      type: talks
    values:
      layout: talk

url: "https://dskill.github.io"
baseurl: "/website"
