title: "Drew Skillman"
tagline: "PLAYABLE REALITIES"
description: "Recreation of the Drew Skillman portfolio homepage."
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

url: "" # Set this to your production URL after publishing.
baseurl: "" # Leave blank when deploying to the root.
